spring:
  application:
    name: mono

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: ${{secrets.DB_URL}}
    username: ${{secrets.DB_USERNAME}}
    password: ${{secrets.DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

google:
  api:
    key: ${{secrets.GOOGLE_KEY}}