spring:
  application:
    name: mono

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  role:
    manager: ${MANAGER_TOKEN}

google:
  api:
    key: ${GOOGLE_KEY}

