server:
  port: 8082

spring:
  application:
    name: mono

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        allow_jdbc_metadata_access: true
        show_sql: true
        format_sql: true
        use_sql_comments: true

google:
  api:
    key: ${GOOGLE_KEY}
role:
  manager: ${MANAGER_TOKEN}