server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: ${{secrets.DB_URL}}
    username: ${{secrets.DB_USERNAME}}
    password: ${{secrets.DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    jwt:
      secret: ${{secrets.JWT_SECRET_KEY}}
      expiration-time: 86400000
      token-prefix: Bearer
      header-string: Authorization
  data:
    redis:
      host: ${{secrets.REDIS_HOST}}
      port: ${{secrets.REDIS_PORT}}

app:
  user:
    default-role: CUSTOMER
