server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: ${{secrets.DB_URL}}
    username: ${{secrets.DB_USERNAME}}
    password: ${{secrets.DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: ${{secrets.REDIS_HOST}}
      port: ${{secrets.REDIS_PORT}}
      password: ${{sercrets.REDIS_PASSWORD}}
  app:
    user:
      default-role: CUSTOMER

service:
  jwt:
    secret-key: ${{secrets.JWT_SECRET_KEY}}
    expiration-time: 3600000
    token-prefix: "Bearer "
    header-string: "Authorization"

role:
  manager: ${{secrets.MANAGER_TOKEN}}

