server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    jwt:
      secret: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
      expiration-time: 86400000
      token-prefix: Bearer
      header-string: Authorization
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  user:
    default-role: CUSTOMER
