server:
  port: 8080

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway
  cloud:
    gateway:
      routes:  # Spring Cloud Gateway의 라우팅 설정
        - id: auth-service  # 라우트 식별자
          uri: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
          predicates:
            - Path=/auth/**  # /auth/** 경로로 들어오는 요청을 이 라우트로 처리
        - id: monolithic-service  # 라우트 식별자
          uri: http://${MONO_SERVICE_HOST}:${MONO_SERVICE_PORT}
          predicates:
            - Path=/api/**  # /api/** 경로로 들어오는 요청을 이 라우트로 처리
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
    token-prefix: "Bearer "
    header-string: "Authorization"

auth:
  server:
    url: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
