name: Deploy to EC2

on:
  push:
    branches:
      - main # 배포할 브랜치 설정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR files
        run: |
          cd com.foodtogo.mono
          ./gradlew build
          cd ../com.foodtogo.auth
          ./gradlew build
          cd ../com.foodtogo.gateway
          ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          # Gateway
          docker build --platform linux/amd64 -t ttlcc13/foodtogo-gateway:latest ./com.foodtogo.gateway
          docker push ttlcc13/foodtogo-gateway:latest
          
          # Auth
          docker build --platform linux/amd64 -t ttlcc13/foodtogo-auth:latest ./com.foodtogo.auth
          docker push ttlcc13/foodtogo-auth:latest
          
          # Mono
          docker build --platform linux/amd64 -t ttlcc13/foodtogo-mono:latest ./com.foodtogo.mono
          docker push ttlcc13/foodtogo-mono:latest

      - name: 1st Deploy to EC2 (auth-service, mono-service)
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem $USER@$HOST << 'EOF'
            docker compose -f app-compose.yml down
            docker compose -f app-compose.yml up -d
          EOF
      - name: 2nd Deploy to EC2 (gateway-service)
        env:
          HOST: ${{ secrets.EC2_HOST_GW }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem $USER@$HOST << 'EOF'
            docker compose -f app-compose.yml down
              docker compose -f app-compose.yml up -d
            EOF
